apiVersion: v1
kind: Secret
metadata:
  name: correnteauth-postgresql
  namespace: default
  labels:
    app: correnteauth-postgresql
type: Opaque
data:
  postgres-password: cGl4MHI4djQ=
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: correnteauth-postgresql
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: correnteauth-postgresql
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: postgres
        image: postgres:10.4
        env:
        - name: POSTGRES_USER
          value: correnteauth
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: correnteauth-postgresql
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/
---
apiVersion: v1
kind: Service
metadata:
  name: correnteauth-postgresql
  namespace: default
spec:
  selector:
    app: correnteauth-postgresql
  ports:
  - port: 5432
