apiVersion: v1
kind: Service
metadata:
  name: corrente
  namespace: default
  labels:
    app: corrente
spec:
  selector:
    app: corrente
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
